### ISSUE TITLE
Is there a Drupal 8 (9, 10) implementation?

### ISSUE THREAD

**Issue by MPParsley** [Esri/drupal-map-gallery-webmaps#7]
Drupal 7 will be EOL in November, do you have a more recent module for Drupal 8+?

**Comment by mhogeweg** [comment]
hi, there is no plan to port the Drupal map gallery to Drupal 8+.

**Comment by MPParsley** [comment]
OK, thank you.

Any idea if there are other modules that provide webmap integration?

**Comment by mhogeweg** [comment]
One approach is to use the [iframe module](https://www.drupal.org/project/iframe) and embed [single apps](https://doc.arcgis.com/en/arcgis-online/create-maps/create-map-apps.htm) or [group apps](https://doc.arcgis.com/en/arcgis-online/create-maps/create-gallery-apps.htm) in a drupal page.

**Comment by MPParsley** [comment]
Thank you for the input!
